name: AutoRelease

on:
  push:
    paths:
      - 'index.xml'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  createrelease:
    runs-on: ubuntu-latest

    steps:
    - uses: phish108/autotag-action@1.1.37
      with:
        github-token: ${{ secrets.GITHUB_TOKEN}}
        with-v: "true"
        bump: minor
